# Generated by Django 4.2.5 on 2024-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('concert', 'Concert'), ('others', 'Others')], default='birthday', max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('event_venue', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('members_required', models.IntegerField()),
                ('seating_arrangement', models.CharField(max_length=255)),
                ('event_signpage_preference', models.CharField(max_length=255)),
                ('event_duration', models.IntegerField()),
                ('estimated_guests', models.IntegerField(default=0)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
