# Generated by Django 4.2.5 on 2024-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_eventregister_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
