# Generated by Django 4.2.5 on 2024-03-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_eventregister_members_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='seating_arrangement',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
