# Generated by Django 4.2.5 on 2024-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_eventregister_event_signpage_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='event_duration',
            field=models.IntegerField(null=True),
        ),
    ]
