# Generated by Django 4.2.5 on 2024-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_eventregister_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='estimated_guests',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
