# Generated by Django 4.2.5 on 2024-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_eventregister_estimated_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='event_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
