# Generated by Django 4.2.5 on 2023-12-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0002_eventregister_estimated_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='event_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='event_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='event_signpage_preference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='event_venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='members_required',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='seating_arrangement',
            field=models.CharField(max_length=255),
        ),
    ]
