# Generated by Django 4.2.5 on 2023-12-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0004_alter_eventregister_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('concert', 'Concert'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
