# Generated by Django 4.2.5 on 2024-01-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0006_alter_eventregister_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Rajasthan', 'Rajasthan'), ('Maharashtra', 'Maharashtra'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Delhi', 'Delhi')], max_length=255)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('cvv', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='eventregister',
            name='billing_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventify.billinginformation'),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='payment_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventify.paymentinformation'),
        ),
    ]
