# Generated by Django 4.2.5 on 2024-01-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0011_eventregister_billing_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='billing_info',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='eventify.billinginformation'),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='payment_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eventify.paymentinformation'),
        ),
    ]
