# Generated by Django 4.2.5 on 2024-01-05 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventify', '0012_alter_eventregister_billing_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregister',
            name='billing_info',
        ),
        migrations.RemoveField(
            model_name='eventregister',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='eventregister',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
