# Generated by Django 4.2.5 on 2024-01-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0013_remove_eventregister_billing_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregister',
            name='user',
        ),
    ]
