# Generated by Django 4.2.5 on 2024-03-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0014_remove_eventregister_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegister',
        ),
    ]
