# Generated by Django 4.2.5 on 2024-03-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0015_delete_eventregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInformation',
        ),
        migrations.DeleteModel(
            name='PaymentInformation',
        ),
    ]
